[2025-04-18T13:46:52.735+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T13:46:52.929+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: entsoe_etl_germany.extract_data scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2025-04-18T13:46:52.971+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: entsoe_etl_germany.extract_data scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2025-04-18T13:46:52.972+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-18T13:47:12.980+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_data> on 2024-03-12 00:00:00+00:00
[2025-04-18T13:47:13.344+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=111) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-18T13:47:13.513+0000] {standard_task_runner.py:72} INFO - Started process 134 to run task
[2025-04-18T13:47:13.514+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'entsoe_etl_germany', 'extract_data', 'scheduled__2024-03-12T00:00:00+00:00', '--job-id', '719', '--raw', '--subdir', 'DAGS_FOLDER/entsoe_germany_dag.py', '--cfg-path', '/tmp/tmpha9nfnkm']
[2025-04-18T13:47:13.585+0000] {standard_task_runner.py:105} INFO - Job 719: Subtask extract_data
[2025-04-18T13:47:15.998+0000] {task_command.py:467} INFO - Running <TaskInstance: entsoe_etl_germany.extract_data scheduled__2024-03-12T00:00:00+00:00 [running]> on host 14a4bb8d64b8
[2025-04-18T13:47:22.847+0000] {job.py:229} INFO - Heartbeat recovered after 36.11 seconds
[2025-04-18T13:47:28.091+0000] {local_task_job_runner.py:266} INFO - Task exited with return code -9. For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed
[2025-04-18T13:47:29.316+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T13:47:29.351+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-18T13:47:29.690+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
